### ISSUE TITLE
StackOverflowError when transactional controller method calls super class' method

### ISSUE THREAD

**Issue by gubespam** [grails/grails-core#10088]
### Task List
- [ ] Example that reproduces the problem uploaded to Github
### Steps to Reproduce
1. Create a domain class and controller. The controller class should extend RestfulController.
2. Generate views for the domain class.
3. Add a method to the controller, named "save", as below:

```
    def save() {
        super.save()
    }
```
1. Go to the domain class page and create a new domain instance. When you click "Save", you will receive a StackOverflowError.
### Stack Trace

The StackOverflowError trace has the following three lines repeated over and over:

```
at com.example.grails.controller.BookController$$EPsvqM2j.$tt__save(BookController.groovy:97)
at grails.transaction.GrailsTransactionTemplate$2.doInTransaction(GrailsTransactionTemplate.groovy:96)
at grails.transaction.GrailsTransactionTemplate.execute(GrailsTransactionTemplate.groovy:93)
```

Notice that RestfulController has a @Transactional annotation on the save() method. My hunch is that the AST transformation which applies the @Transactional annotation has a bug wherein the resulting AST blindly calls the method ("save" in this case) on the instance's class (which results in the subclass's "save" method being called) instead of directly calling the base class' method (which is where the @Transactional attribute is).

The AST transformation is `org.codehaus.groovy.grails.transaction.transform.TransactionalTransform`
### Environment Information
- **Operating System**: Windows 7, 64 bit
- **Grails Version:** 3.1.5
- **JDK Version:** 1.8.0u45
- **Container Version (If Applicable):** N/A
### Example Application
- I do not have the ability to create a test github project (to reproduce) where I am at now. I may be able to do this at a later time, if I have the opportunity. If someone else is willing to do this, please do; the full steps are described above.

**Comment by gubespam** [comment]
The AST transform works by creating a new method named $tt__X, where X is the original method name. The code in X is move to this new method, and the code X is replaced with the transaction-handling code and a call to $tt__X.

I pulled my code up in a debugger, and was able to get a more details stack trace of the issue. See attached file (which actually has the class hierarchy: BookController -> RestfulControllerSubclass -> RestfulController).

The important part is the first two line at the top of the stack:
```
BookController.$tt__update(TransactionStatus) line: not available	
RestfulController$_update_closure6.doCall(TransactionStatus) line: not available	
```

Here you can see that the transformed RestfulController method is calling the subclass' renamed method $tt__update instead of calling method by the same name on the RestfulController class.

If you look at the code in AST transform class, in method weaveTransactionalMethod, there is this line:

`final callCallExpression = new ClosureExpression(executeMethodParameterTypes, createTransactionalMethodCallBody(transactionStatusParam, originalMethodCall))`

And `createTransactionalMethodCallBody` simply contains the line: `new ExpressionStatement(originalMethodCall)`

That's just a regular method call, and thus it will be routed to the method by that name ($tt__update) on the subclass (BookController), rather than on the base class (RestfulController).

So something needs to be done to prevent this call from the base class from being routed to the subclass.

Perhaps one solution would be to ensure that renamed methods are named uniquely within a class hierarchy; this would prevent the code in the transformed base class method from calling the subclass. For example, the new method in the base class (RestfulController) might be named $tt__1_update and the subclass (BookController) might be named $tt__1_update. That would ensure the proper method is called, since the names are unique.

**Comment by gubespam** [comment]
[stack_trace.txt](https://github.com/grails/grails-core/files/402629/stack_trace.txt)

**Comment by gubespam** [comment]
I found a workaround, assuming that the method in question does not need a transaction: Adding the @NotTransactional annotation to the subclass method prevent the AST transform from running on that method in the subclass. Of course, this isn't an option if the subclass method needs a transaction.

**Comment by Schlogen** [comment]
This is most likely why: https://github.com/grails/grails-core/blob/dcfa7e120e923444bf041b89eea59cdeac70c552/grails-core/src/main/groovy/org/grails/transaction/transform/TransactionalTransform.groovy#L350

Implicit this is false so it is then calling the method on the subclass

**Comment by jameskleeh** [comment]
@graemerocher Does the fix I commented above seem reasonable?

**Comment by graemerocher** [comment]
seems reasonable yes

**Comment by jameskleeh** [comment]
@gubespam I was unable to reproduce this with 3.2. Please create an example project

**Comment by dpcasady** [comment]
I've experienced the same issue. Here's an example app using 3.2.8: https://github.com/dpcasady/transactional-overflow-example

Run the tests and you should see the StackOverflowError.

**Comment by dpcasady** [comment]
Oh and FYI, it seems to happen regardless of whether [grails.transaction.Transactional](https://github.com/grails/grails-core/blob/master/grails-core/src/main/groovy/grails/transaction/Transactional.java) or [grails.gorm.transactions.Transactional](https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm/src/main/groovy/grails/gorm/transactions/Transactional.java) (GORM 6.1) is used.

**Comment by graemerocher** [comment]
Fix requires upgrading to GORM 6.1.2

**Comment by dpcasady** [comment]
@graemerocher this is still failing for me with Grails 3.2.9 and GORM 6.1.2. I've updated the example project to use those versions: https://github.com/dpcasady/transactional-overflow-example. The unit tests still fail with a StackOverflowError.

**Comment by dpcasady** [comment]
Nevermind, using `grails.gorm.transactions.Transactional` does work now, it's just the old annotation that still fails.

**Comment by snimavat** [comment]
@graemerocher @jameskleeh can we have the fix in grails 3.2.x branch --- because gorm 6.1.x comes with many new features and not every one can migrate to new gorm just for working around this bug.

Gorm 6.1.x has some non backward compitible changes.

We are facing this issue with grails 3.2.8 and Gorm 6.0.9.RELEASE. 

Calling super class method from a transactional service is a very common usage, it should not force to upgrade to a gorm version which has major changes... however upgrading to a newer grails maintenance release would work.

**Comment by graemerocher** [comment]
No, the transform has been rewritten completely and would be too complicated to backport

**Comment by snimavat** [comment]
Is grails 3.2.8 supposed to work with Gorm 6.1.4 ?

I am seeing below errors 

```
General error during canonicalization: java.lang.NoClassDefFoundError: Unable to load class grails.test.mixin.domain.DomainClassUnitTestMixin due to missing dependency org/grails/datastore/mapping/simple/SimpleMapDatastore

java.lang.RuntimeException: java.lang.NoClassDefFoundError: Unable to load class grails.test.mixin.domain.DomainClassUnitTestMixin due to missing dependency org/grails/datastore/mapping/simple/SimpleMapDatastore

```

**Comment by snimavat** [comment]
Alright, i see

testCompile "org.grails:grails-datastore-gorm-test:$gormVersion"

**Comment by snimavat** [comment]
@graemerocher looks like its still not fixed completely, plz see issue #10681
