### ISSUE TITLE
[3.1.3] New validateable features break gradle compilation when using validateable class from Java

### ISSUE THREAD

**Issue by mTatai** [grails/grails-core#9774]
In Grails 3.1.2 and 3.1.3 using a class in that implements Validateable in a Java file breaks the compileGroovy task of gradle. Interestingly, it compiles with IntelliJ IDEA's compiler.
The same thing compiles with Grails 3.1.1 (So I guess the issue is with the new validateable changes).

A minimal setup to reproduce the issue:

`sdk u grails 3.1.3`
`grails create-app validateable313`
`cd validateable313/`

Add `SomeValidateable.groovy` and `JavaUser.java` to src/main/groovy

```
import grails.validation.Validateable

class SomeValidateable implements Validateable {
}
```

```
public class JavaUser {
    SomeValidateable someValidateable;
}
```

`./gradlew clean compileGroovy`

Produces the output:
```
projectDir/validateable313/build/tmp/compileGroovy/groovy-java-stubs/SomeValidateable.java:17: error: cannot find symbol
@org.codehaus.groovy.transform.trait.Traits.Implemented() public  boolean validate(java.util.List param0, groovy.lang.Closure<V>... param1) { return false;}
                                                                                                                              ^
  symbol:   class V
  location: class SomeValidateable
projectDir/validateable313/build/tmp/compileGroovy/groovy-java-stubs/SomeValidateable.java:18: error: cannot find symbol
@org.codehaus.groovy.transform.trait.Traits.Implemented() public  boolean validate(java.util.List param0, java.util.Map<java.lang.String, java.lang.Object> param1, groovy.lang.Closure<V>... param2) { return false;}
                                                                                                                                                                                        ^
  symbol:   class V
  location: class SomeValidateable
projectDir/validateable313/build/tmp/compileGroovy/groovy-java-stubs/SomeValidateable.java:19: error: cannot find symbol
@org.codehaus.groovy.transform.trait.Traits.Implemented() public  boolean validate(groovy.lang.Closure<V>... param0) { return false;}
                                                                                                       ^
  symbol:   class V
  location: class SomeValidateable
projectDir/validateable313/build/tmp/compileGroovy/groovy-java-stubs/SomeValidateable.java:20: error: cannot find symbol
@org.codehaus.groovy.transform.trait.Traits.Implemented() public  boolean validate(java.util.Map<java.lang.String, java.lang.Object> param0, groovy.lang.Closure<V>... param1) { return false;}
                                                                                                                                                                 ^
  symbol:   class V
  location: class SomeValidateable
projectDir/validateable313/build/tmp/compileGroovy/groovy-java-stubs/SomeValidateable.java:8: error: SomeValidateable is not abstract and does not override abstract method validate(List,Map<String,Object>,Closure...) in Validateable
public class SomeValidateable
       ^
projectDir/validateable313/build/tmp/compileGroovy/groovy-java-stubs/SomeValidateable.java:17: error: name clash: validate(List,Closure<V>...) in SomeValidateable and validate(List,Closure...) in Validateable have the same erasure, yet neither overrides the other
@org.codehaus.groovy.transform.trait.Traits.Implemented() public  boolean validate(java.util.List param0, groovy.lang.Closure<V>... param1) { return false;}
                                                                          ^
projectDir/validateable313/build/tmp/compileGroovy/groovy-java-stubs/SomeValidateable.java:18: error: name clash: validate(List,Map<String,Object>,Closure<V>...) in SomeValidateable and validate(List,Map<String,Object>,Closure...) in Validateable have the same erasure, yet neither overrides the other
@org.codehaus.groovy.transform.trait.Traits.Implemented() public  boolean validate(java.util.List param0, java.util.Map<java.lang.String, java.lang.Object> param1, groovy.lang.Closure<V>... param2) { return false;}
                                                                          ^
projectDir/validateable313/build/tmp/compileGroovy/groovy-java-stubs/SomeValidateable.java:19: error: name clash: validate(Closure<V>...) in SomeValidateable and validate(Closure...) in Validateable have the same erasure, yet neither overrides the other
@org.codehaus.groovy.transform.trait.Traits.Implemented() public  boolean validate(groovy.lang.Closure<V>... param0) { return false;}
                                                                          ^
projectDir/validateable313/build/tmp/compileGroovy/groovy-java-stubs/SomeValidateable.java:20: error: name clash: validate(Map<String,Object>,Closure<V>...) in SomeValidateable and validate(Map<String,Object>,Closure...) in Validateable have the same erasure, yet neither overrides the other
@org.codehaus.groovy.transform.trait.Traits.Implemented() public  boolean validate(java.util.Map<java.lang.String, java.lang.Object> param0, groovy.lang.Closure<V>... param1) { return false;}
                                                                          ^
Note: projectDir/validateable313/build/tmp/compileGroovy/groovy-java-stubs/SomeValidateable.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

**Comment by jeffbrown** [comment]
Related to #9761.

**Comment by jeffbrown** [comment]
Related to #9761
