### ISSUE TITLE
Grails 3.3.0.M2 compilation error for a service which extends another service which declares a log property. 

### ISSUE THREAD

**Issue by sdelamo** [grails/grails-core#10683]
Given a service: 

```
package demo

class ChildService extends ParentService {

    def bar() {
	log.info("hello world")
    }
}
```

If the Parent service, which the previous service extends from,  defines a logger property such as: 

```
package demo

import org.slf4j.Logger
import org.slf4j.LoggerFactory

class ParentService {

    protected Logger log = LoggerFactory.getLogger(getClass())

    def foo() {
	log.info("hello world")
    }
}
```

It compiles in Grails 3.2.10 

but in Grails 3.3.0.M2 it does not compile with: 

```
/Users/sdelamo/Developer/tests/extending_from_a_service_with_logger/grails_three_three/grails-app/services/demo/ChildService.groovy: 8: Class annotated with Log annotation cannot have log field declared because the field exists in the parent class: demo.ParentService
 @ line 8, column 5.
   }
       ^

/Users/sdelamo/Developer/tests/extending_from_a_service_with_logger/grails_three_three/grails-app/services/demo/ParentService.groovy: 8: Class annotated with Log annotation cannot have log field declared
 @ line 8, column 5.
       protected Logger log = LoggerFactory.getLogger(getClass())
       ^
```

**Workaround**

Replacing the property with @Slf4j annotation such as.

```
package demo
import groovy.util.logging.Slf4j

@Slf4j
class ParentService {
    def foo() {
	log.info("hello world")
    }
}
```

or just removing it completely: 

```

package demo

class ParentService {
    def foo() {
	log.info("hello world")
    }
}
```

I discovered the problem while working with plugins which have such as log property such as services in Spring Security Core Plugin. 

https://github.com/grails-plugins/grails-spring-security-core/blob/master/src/main/groovy/grails/plugin/springsecurity/userdetails/GormUserDetailsService.groovy#L36

### Steps to reproduce

Clone the linked repository (see example application below). 

go to `grails_three_three` folder

run ./gradlew compileGroovy

### Environment Information

- **Operating System**: MacOS
- **Grails Version:** 3.2.10 & 3.3.0.M2
- **JDK Version:** TODO
- **Container Version (If Applicable):** TODO

### Example Application

https://github.com/grails-core-issues-forks/grails-core-issue-10683
