### ISSUE TITLE
Grails 2.4.0: Java 8u40 w/ 2.4.5/2.5 gives $getStaticMetaClass() visibility errors in inheriting controllers

### ISSUE THREAD

**Issue by patric42** [grails/grails-core#619]
Grails 2.4.5/2.5.0 with Java 8u40

Given two controllers:
- abstract SecureController
- UserController extends SecureController

On clean compile, it works, but if changed and recompiled in dev mode, it gives
| Compiling 1 source files
  [groovyc] org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  [groovyc] /.../grails-app/controllers/UserController.groovy: -1: $getStaticMetaClass() in UserController cannot override $getStaticMetaClass in SecureController; attempting to assign weaker access privileges; was public
  [groovyc]  @ line -1, column -1.

Switching to 8u31, it works again. I tried moving the SecureController to src/groovy, to no avail.

**Comment by bxqgit** [comment]
I confirm, this error occures.

**Comment by burtbeckwith** [comment]
8u45 was released recently - can you try upgrading?

**Comment by patric42** [comment]
Still happens with 8u45, just tried.

**Comment by zyro23** [comment]
might be related: https://github.com/jamescookie/quartz-monitor/issues/30

and behavior confirmed. working with jdk 8u31, fails with 8u45...

however, i can not see a reason for `attempting to assign weaker access privileges`. all method definitions (the overriding ones and the overridden ones) are protected. nothing `was public`...

maybe sth. is going on with groovy-2.4.3 and jdk-8u40+?

**Comment by jmesterh** [comment]
Also seeing this issue with 8u45, with a domain class extending an abstract class in src/groovy

**Comment by zyro23** [comment]
@jeffbrown @graemerocher do you maybe have any idea what could be the cause of this? at least for me, avoiding jdk 8u40+ is not possible for long. thanks, zyro

**Comment by zyro23** [comment]
i think i was able to isolate this a bit further. using jdk 8u45 and grails-2.5.0. given the following classes:
```java
// src/main/java/jdktest/JavaClass.java
public class JavaClass {
	protected void foo() {}
}
```
```groovy
// src/main/groovy/jdktest/GroovyClass.groovy
class GroovyClass extends JavaClass {
	@Override
	protected void foo() {}
}
```
* `grails run-app`: compilation error: `foo() in jdktest.GroovyClass cannot override foo in jdktest.JavaClass; attempting to assign weaker access privileges; was public`
* `grails compile`: works
* `grails compile`, then `grails run-app`: works
* `grails clean`, then `grails run-app`: again compilation error from above

@patric42 @bxqgit @jmesterh can you confirm that compilation and subsequent run-app works after manually doing a `grails compile`?

**Comment by patric42** [comment]
As I wrote in the initial report: Initial compile works, but recompile through the agent seems broken.

**Comment by dacoates** [comment]
I have same problem as zyro23. Grails 2.5.0, Java 8u45. Only compile that works is the first one following a clean.

**Comment by tnleeuw** [comment]
I've seen the exact same error, both on Quartz + Quartz Monitor and on my own code - but only when compiling from within grails run-app.

When running grails compile, I do not see this kind of behaviour at all - compilation works as expected.

**Comment by nmfisher** [comment]
Same issue here after upgrading to 8u45

**Comment by dacoates** [comment]
Java 8u31 and earlier does not have this problem, but Java 8u45 does.

**Comment by agileheat** [comment]
I'm new to grails, but yes i found this with 8u40 and 8u45 too - it works on 8u31

**Comment by tnleeuw** [comment]
Since Groovy/Grails behaviour changed with a JDK update, should this be seen as a JDK bug? Or is it a change in JDK that is unavoidable due to security fixes, that Groovy/Grails will have to adapt to somehow?

**Comment by ivgeorgi** [comment]
Any updates on this issue.

**Comment by graemerocher** [comment]
Someone please upload an example to Github with steps to reproduce

**Comment by zyro23** [comment]
here you go: https://github.com/zyro23/grails-core-619 - can reproduce the issue with jdk 8u45 (clean run-app).
btw: nice to see you back at work, graeme :)

**Comment by ikakara** [comment]
Graeme - others are reporting that this issue also occurs for domain classes (see https://github.com/grails/grails-core/issues/682)

**Comment by ikakara** [comment]
Graeme - I've just discovered this to be a more general problem w/ groovy classes inheriting from groovy sub-classes. https://github.com/grails/grails-core/issues/682

**Comment by graemerocher** [comment]
@zyro23 Using your example I can only reproduce if I change `GroovyClass` at runtime. Using `clean -> run-app' or any combination of clean or not clean state to run the application works fine for me using 1.8 update 45

**Comment by graemerocher** [comment]
So I did some debugging and it seems at runtime that when I reflect on the Java super class the `foo` method is `public`, even though it is declared as `protected` in the source. Maybe @aclement knows if Spring Loaded is changing visibility modifiers on classes at runtime?

**Comment by graemerocher** [comment]
I can confirm that disabling Spring Loaded fixes this problem at runtime, so definitely a Spring Loaded bug. @aclement Any ideas?

**Comment by aclement** [comment]
>  Maybe @aclement knows if Spring Loaded is changing visibility modifiers on classes at runtime?
Yes it does for the classes that actually get defined but it also instruments reflection so that when you ask the question via reflection you should get the original correct answer. If you don't then that is a bug.

**Comment by graemerocher** [comment]
@aclement Via reflection I get that the method is public when it is defined as protected so there seems to be a bug here :(

**Comment by ikakara** [comment]
Any update on the progress of this bug?

**Comment by graemerocher** [comment]
As mentioned it is a Spring Loaded bug, using the steps provided by @zyro23 I can reproduce and disabling Spring Loaded makes the problem go away. We will need a new release of Spring Loaded, to resolve it, which depends very much on @aclement and how much free time he has to look at this.

**Comment by aclement** [comment]
Not sure what I'm doing wrong but it won't fail for me. I have grails 2.5 with java 1.8.0_45 on mac. I 'create-app test' then added the two source files mentioned in zyro23's comment on Apr 27 (I added package statements to them which I presume were needed). Then grails run-app, works. Tried grails clean then run-app, works too.  Maybe I need some even simpler instructions...?

> Via reflection I get that the method is public when it is defined as protected so there seems to be a bug here :(

Which reflective call made in the grails code is returning the wrong answer? Or is this one that was just inserted for debugging purposes?

**Comment by ikakara** [comment]
@aclement, you need to cause a reason to recompile/reload (via spring-loaded)... For example, add a (new) line to the subclass.  
```
> grails clean
> grails compile // doesn't use spring-loaded
> grails run-app // uses spring-loaded
// above should run fine
// make a change to the subclas (while in run-app); grails will recompile and try to reload, and fail

// to see the error, you have to perform "grails run-app", but you can run it anytime after the change to the subclass, assuming you're not performing a "grails compile" which doesn't use spring-loaded to recompile/reload the subclass
```

**Comment by tnleeuw** [comment]
personally, for me it fails with just

    > grails clean
    > grails run-app

Another scenario that causes failure for me is a default grails-app that contains nothing but Quartz & Quartz Monitor plugins:

    plugins {
    // ....
            compile ':quartz:1.0.2'
            compile ':quartz-monitor:1.0'
    
    // ....
    }

For me the following 2 classes are sufficient to reproduce:

-------------
    package grailscompiletest
    
    class BaseClass {
        protected int  foo() { return 1 }
    }
    
------------------
    package grailscompiletest
    
    class SubClass extends BaseClass {
        @Override
        protected int foo() { return 2 }
    }
    
------------------

Like I said above, start with:

    > grails clean
    > grails run-app

Or, if pre-compiled, then cause a recompilation to be triggered while the app is running.

(Trying to work out where I can attach my test project)

**Comment by ikakara** [comment]
@tnleeuw - thanks, that was a much cleaner fail case

@aclement - any luck?

**Comment by aclement** [comment]
I have now found some more time to look at it, and recreated it. I decided to use the 'modify it to trigger a reload' solution.  I feel debugging a run-app that is also doing compilation as part of its work is more difficult, much more stuff to dig through. So a `grails compile` and then a separate `grails run-app` I can debug is easier. I'm afraid you do have to dumb things down for me sometimes as I don't write grails code every day :)

The problem is a knock on effect of the recent change introduced to cope with changes in the JDK a little while ago. (the fact that the JVM method copying code now only allows the 'root' method to be copied - you can no longer copy a copy). The original version of this fix always jumped back to the root and copied that. However in the situation uncovered here the original method has the 'public' modifier, only the copy we were working with has 'protected'.  So by jumping back to root rather than using what we had, we fell back on the 'public' modifier (the wrong modifier).

However, from what I observed, it seems a possible fix already went in to spring loaded to address this but it is only in dev builds, not in a release yet. The alternative fix was to trick the JDK method copying so it did not mind copying-a-copy. With this solution we keep the protected modifier. I'd forgotten about it because it was a while ago (the alternative fix went in during March). So try running with this spring loaded snapshot from:

http://repo.spring.io/libs-snapshot-local/org/springframework/springloaded/1.2.4.BUILD-SNAPSHOT/springloaded-1.2.4.BUILD-20150506.053454-9.jar

When I do, the problem is gone.

**Comment by graemerocher** [comment]
@aclement Thanks for looking into this, any idea when 1.2.4 will be released?

**Comment by aclement** [comment]
If you tell me this does address these problems, we can do it pretty quick.

**Comment by ikakara** [comment]
@aclement - How do I test your jar?  I've tried the following in the conf/BuildConfig.groovy

```
  repositories {
    inherits true // Whether to inherit repository definitions from plugins

    grailsPlugins()
    grailsHome()
    mavenLocal()
    grailsCentral()
    mavenCentral()

    mavenRepo "http://repo.spring.io/libs-snapshot-local/org/springframework/springloaded/1.2.4.BUILD-SNAPSHOT/"
  }
  management {
    dependency "org.springframework:springloaded:'1.2.4.BUILD-20150506.053454-9'"
  }
```

**Comment by aclement** [comment]
It is crude... but I usually download it and replace the one in grails with it (i.e. rename what I download to the same name as the version inside grails).

**Comment by ikakara** [comment]
I noticed an extra set of quotes in my example - still didn't work, when fixed the quotes.  Ok, I'll give the rename a try ...

**Comment by ikakara** [comment]
Works for me!  I say ship it!  lol

For full disclosure, I just tested my broken case where I do a grails run-app (w/o first compile) which normally reproduces the error, and I also tried modifying a subclass (during grails run-app), which will also reproduce the error.  Those two cases are fixed with the latest jar.

**Comment by ikakara** [comment]
@aclement - is there a unit test for "modify subclass"?

There are only 2 open bugs for 2.5.1 and they both appear to be a simple config change for graeme (assuming aclement builds v1.2.4 of springloaded).  So 2.5.1 can go live by tomorrow :+1:

**Comment by aclement** [comment]
>  is there a unit test for "modify subclass"?
There is - but I doubt there is one for every combination of visibility.

**Comment by ikakara** [comment]
@aclement - no worries - add them when we find them :)  Do you have eta on release of 1.2.4?

Also there's another springloaded issue: https://github.com/grails/grails-core/issues/599  - I went ahead and tried your 1.2.4 snapshot (w/ Grails 3), and it didn't fix the problem.  I didn't think the bug was related to this one, but I tried anyway ... to no avail.

**Comment by ikakara** [comment]
@aclement - any status on the release (eta) of 1.2.4?

**Comment by graemerocher** [comment]
I believe @aclement plans to release it soon, we are coordinating with him

**Comment by rgoldberg** [comment]
@aclement & @graemerocher: Do you have an ETA for Spring Loaded 1.2.4 being released & included in Grails 2.5.1, and for Grails 2.5.1 being released?

I'm about to start testing an upgrade from a much older version of Grails, and from Java 7 to Java 8u31.

If Grails 2.5.1 will be ready in less than a week or so, then I'll probably wait for it.

Otherwise, I'll probably test & release the upgrade to 2.5.0 & 8u31, and then later test & release a second upgrade to 2.5.1 & 8u45.

Thanks for all your work on both projects.

**Comment by jeffbrown** [comment]
#9136 should fix this.

**Comment by kasonyang** [comment]
Is it fixed?It occures when I use grails 3.0.6 && java 8u45.

**Comment by tnleeuw** [comment]
For me, this is fixed in Grails 2.5.1 and Java 8u60. Although I believe
that the java version isn't actually relevant for the fix. Which version of
SpringLoaded I'd included in Grails 3.0.6?

--Tim

**Comment by kasonyang** [comment]
@tnleeuw  springloaded-1.2.4.RELEASE.jar

**Comment by tnleeuw** [comment]
@Kason That's the same version as in Grails 2.5.1, so this should be Ok. I
wonder if it still is also depending on Java version then? Or if somehow
something got screwed up in the loading of libraries, taking an older
version from an unexpected place on the classpath, somehow??

**Comment by kasonyang** [comment]
@tnleeuw  Thanks! It seams that the project cache the old libraries. I create a new project with grails3.06 and copy the source from the old project then run the new project.The problem disappear.

**Comment by tnleeuw** [comment]
What if you do "grails clean all" in the old project directory?

**Comment by kasonyang** [comment]
I did it(`grails clean all`) in the old project unsuccessfully.
Here is output:
```
> Configuring > 0/1 projects > root project > Resolving dependenc1/1 projects > Resolving dependencies ':agent' > Resolving depend
BUILD SUCCESSFUL

Total time: 54.552 secs
> Resolving dependencies ':testRuntime' > Resolving dependencies | Error Error initializing classpath: Unsupported method: GrailsClasspath.getError().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model. (Use --stacktrace to see the full trace)
```
My gradle version is 2.7

**Comment by tnleeuw** [comment]
Sorry, I don't know enough about Gradle & Grails 3 yet to be helpful with
this error...
I do see that Gradle 2.7 is the latest official release of Gradle, but
perhaps it is too new??
Did you try upgrading to Grails 3.0.8? Or Gradle 2.8rc1?

--Tim

**Comment by kasonyang** [comment]
@tnleeuw Yes.It is too new.I build the old project unsuccessfully with gradle2.7 but successfully with gradle2.4.
However it is not important to me now.There is no problem in my new project.

**Comment by tnleeuw** [comment]
Wondering if newer versions of Grails fix this error with Gradle, though?
