### ISSUE TITLE
Grails plugin include doesn't compile in 2.4.4

### ISSUE THREAD

**Issue by mreid062** [grails/grails-core#626]
[groovyc] org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
  [groovyc] Compile error during compilation with javac.
  [groovyc] C:\Users\default.SID18883\Documents\NetBeansProjects\Budget1\Budget(NB1)\target\work\plugins\include-0.3\src\java\org\grails\include\IncludeWebUtils.java:57: error: cannot find symbol
  [groovyc]         String includeUrl = WebUtils.buildDispatchUrlForMapping(info);
  [groovyc]                                     ^
  [groovyc]   symbol:   method buildDispatchUrlForMapping(UrlMappingInfo)
  [groovyc]   location: class WebUtils
  [groovyc] C:\Users\default.SID18883\Documents\NetBeansProjects\Budget1\Budget(NB1)\target\work\plugins\include-0.3\src\java\org\grails\include\IncludeWebUtils.java:61: error: cannot find symbol
  [groovyc]         WebUtils.exposeForwardRequestAttributes(request);
  [groovyc]                 ^
  [groovyc]   symbol:   method exposeForwardRequestAttributes(HttpServletRequest)
  [groovyc]   location: class WebUtils
  [groovyc] Note: Some input files use unchecked or unsafe operations.
  [groovyc] Note: Recompile with -Xlint:unchecked for details.
  [groovyc] 2 errors
  [groovyc]

**Comment by burtbeckwith** [comment]
This is an issue with the plugin, not Grails, and it's not particularly surprising since the plugin hasn't been updated in _seven_ years.

**Comment by mreid062** [comment]
At some level there is an issue with Grails if plugins that no longer work are available for download without any indication of what versions of Grails are applicable.
